# Generated by Django 3.2.3 on 2024-07-26 05:55

from typing import List, Tuple

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("artist", models.CharField(max_length=250)),
                ("duration", models.FloatField()),
                ("last_play", models.DateTimeField()),
            ],
        ),
    ]
